# Created by: stas
# $FreeBSD: head/devel/mingw64-binutils/Makefile 367080 2014-09-02 20:35:33Z ak $

MAINTAINER= ports@FreeBSD.org

TGTARCH=	x86_64
TGTABI=		w64-mingw32

MASTERDIR=	${.CURDIR}/../cross-binutils
.include "${MASTERDIR}/Makefile"
