# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	go-sqlite3
PORTVERSION=	20150528
CATEGORIES=	databases

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Sqlite3 driver for go that using database/sql

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	mattn
GH_TAGNAME=	542ae647f8601bafd96233961b150cae198e0295

USE_GCC=	yes

GO_PKGNAME=	github.com/mattn/go-sqlite3

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
