# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	zurb-foundation
PORTVERSION=	4.3.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	ZURB Foundation on Sass/Compass

LICENSE=	MIT

RUN_DEPENDS=	rubygem-sass>=3.2.0:${PORTSDIR}/textproc/rubygem-sass

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
