# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTVERSION=	4.15.9546.20150405
MASTER_SITES=	http://www.softether-download.com/files/softether/v${RELEASEVER}-${RELEASEREV}-${RELEASETYPE}-${RELEASEDATE}-tree/Source_Code/
PKGNAMESUFFIX=	-devel

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Cross-platform Multi-protocol VPN Program

CONFLICTS=	softethervpn-[0-9]*

RELEASETYPE=	beta
DISTINFO_FILE=	${.CURDIR}/distinfo
MASTERDIR=	${.CURDIR}/../softethervpn

.include "${MASTERDIR}/Makefile"
