# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw64-
MAINTAINER=	takumiiinn@gmail.com

BUTARGET=	x86_64-w64-mingw32

MASTERDIR=	${.CURDIR}/../binutils
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
