# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	rsync
PORTVERSION=	1.0.9
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Ruby/Rsync is wrapping a call to the rsync binary.

LICENSE=	MIT

RUN_DEPENDS=	rsync>=0:${PORTSDIR}/net/rsync

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
