# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	softethervpn
PORTVERSION=	4.08
RELREVISION=	9449
RELEASEDATE=	2014.06.08
CATEGORIES=	security net
MASTER_SITES=	http://softether-download.com/files/softether/v${PORTVERSION}-${RELREVISION}-rtm-${RELEASEDATE}-tree/Source%20Code/
DISTNAME=	softether-src-v${PORTVERSION}-${RELREVISION}-rtm

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Cross-platform Multi-protocol VPN Program

LICENSE=	GPLv2

USES=		gmake iconv
GNU_CONFIGURE=	YES

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
