# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw-w64-x86_64-
MAINTAINER=	takumiiinn@gmail.com
COMMENT?=	POSIX threads library for Windows compiled with MinGW-w64 x86_64

MASTERDIR=	${.CURDIR}/../mingw-pthreads

.include "${MASTERDIR}/Makefile"
