# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-x86_64-pthreads
MAINTAINER=	takumiiinn@gmail.com
COMMENT?=	POSIX threads library for MinGW-w64 x86_64

MASTERDIR=	${.CURDIR}/../mingw-w64

.include "${MASTERDIR}/Makefile"
