# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw-w64-i686-
MAINTAINER=	takumiiinn@gmail.com
COMMENT=	GNU binary tools for MinGW-w64 i686

MASTERDIR=	${.CURDIR}/../mingw-binutils

.include "${MASTERDIR}/Makefile"
