# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-header
COMMENT=	MinGW-w64 for header files

MASTERDIR=	${.CURDIR}/../mingw64-crt
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
