# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-headers
COMMENT=	MinGW-w64 for header files

WRKSRC_SUBDIR=	${PORTNAME}${PKGNAMESUFFIX}

MASTERDIR=	${.CURDIR}/../mingw-w64
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
