# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-header
COMMENT=	MinGW-w64 for header files

WRKSRC_SUBDIR=	mingw-w64-headers
GNU_CONFIGURE_PREFIX=	${PREFIX}/x86_64-w64-mingw32

MASTERDIR=	${.CURDIR}/../mingw64-crt
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
