# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	i3-py
PORTVERSION=	0.5.5
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Tools for i3 users and developers

LICENSE=	GPLv3

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
