# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	compass-core
PORTVERSION=	1.0.3
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Compass core stylesheet library

LICENSE=	MIT

RUN_DEPENDS=	rubygem-sass>=3.3:${PORTSDIR}/textproc/rubygem-sass \
		rubygem-multi_json>=1.0:${PORTSDIR}/devel/rubygem-multi_json

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
