# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw64-

CROSS_CORE=	yes
CROSS_TARGET=	x86_64-pc-mingw32

MASTERDIR=	${.CURDIR}/../mingw-gcc
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
