# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw64-

CROSS_CORE=	x86_64-pc-mingw32
CROSS_TARGET=	yes

MASTERDIR=	${.CURDIR}/ ../mingw-gcc
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
