# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	gomemcache
PORTVERSION=	20150528
CATEGORIES=	databases

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Go Memcached client library

LICENSE=	APACHE20

USE_GITHUB=	yes
GH_ACCOUNT=	bradfitz
GH_TAGNAME=	72a68649ba712ee7c4b5b4a943a626bcd7d90eb8

GO_PKGNAME=	github.com/bradfitz/gomemcache
GO_TARGET=	github.com/bradfitz/gomemcache/memcache

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
