# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	cli
PORTVERSION=	20150528
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Small package for building command line apps in Go

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	codegangsta
GH_TAGNAME=	942282e931e8286aa802a30b01fa7e16befb50f3

GO_PKGNAME=	github.com/codegangsta/cli

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
