--- make/template/main.mk.orig	2015-05-10 05:24:10 UTC
+++ make/template/main.mk
@@ -60,6 +60,10 @@ INSTMODE_LIB = 0644
 @IFEQ $(SYSTEM) linux
   LDLIBS += -ldl -lrt
 @ENDIF
+@IFEQ $(SYSTEM) freebsd
+  CXXFLAGS += -I/usr/local/include
+  LDFLAGS += -L/usr/local/lib
+@ENDIF
 @IFEQ $(SYSTEM) gnukfreebsd
   LDLIBS += -ldl -lrt
 @ENDIF
@@ -132,7 +136,7 @@ CXXFLAGS += -Iinclude
   CXXFLAGS += -DPURE_STATIC
 @ENDIF
 
-@DO_EXPORT RUNCC RUNLD CXXFLAGS LDLIBS PICLDFLAGS VERBOSE SOCKETENGINE CORELDFLAGS
+@DO_EXPORT RUNCC RUNLD CXXFLAGS LDLIBS PICLDFLAGS VERBOSE SOCKETENGINE CORELDFLAGS LDFLAGS
 @DO_EXPORT SOURCEPATH BUILDPATH PURE_STATIC SPLIT_CC
 
 # Default target
