# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	padrino-helpers
PORTVERSION=	0.12.4
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Elegant Ruby Web Framework

LICENSE=	MIT

RUN_DEPENDS=	rubygem-i18n>=0.6.7:${PORTSDIR}/devel/rubygem-i18n \
		rubygem-padrino-support>=0.12.4:${PORTSDIR}/www/rubygem-padrino-support \
		rubygem-tilt>=1.4.1:${PORTSDIR}/devel/rubygem-tilt1

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
