# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	cli-init
PORTVERSION=	20150528
CATEGORIES=	devel
PKGNAMEPREFIX=	go-

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Easy way to start building Golang command-line application

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	tcnksm
GH_TAGNAME=	55206a554d8a29ddec0bc4f1ccb8d46b2aa5a861

GO_PKGNAME=	github.com/tcnksm/cli-init

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
