# $FreeBSD: head/devel/rubygem-librarian/Makefile 359196 2014-06-25 08:04:23Z robak $

PORTNAME=	librarianp
PORTVERSION=	0.6.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	robak@FreeBSD.org
COMMENT=	Ruby framework for writing bundlers

LICENSE=	MIT

RUN_DEPENDS=	${PKGNAMEPREFIX}thor>=0.15:${PORTSDIR}/devel/rubygem-thor

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
