# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw-w64-x86_64-
MAINTAINER=	takumiiinn@gmail.com
COMMENT=	GCC 4.9 for MinGW-w64 x86_64

MASTERDIR=	${.CURDIR}/../mingw-gcc

.include "${MASTERDIR}/Makefile"
