# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw-w64-x86_64-

MASTERDIR=	${.CURDIR}/../mingw-gcc

# echo '@comment Insert PLIST.lib here' > pkg-plist
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
