# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	foundation
PORTVERSION=	1.0.4
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	A CLI for working with Foundation

LICENSE=	MIT

RUN_DEPENDS=	rubygem-thor>=0.18.1:${PORTSDIR}/devel/rubygem-thor

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/foundation

.include <bsd.port.mk>
