# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-i686-headers
COMMENT=	MinGW-w64 for i686 header files

MASTERDIR=	${.CURDIR}/../mingw-w64
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
