# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-i686-headers
MAINTAINER=	takumiiinn@gmail.com
COMMENT=	MinGW-w64 for i686 header files

MASTERDIR=	${.CURDIR}/../mingw-w64

.include "${MASTERDIR}/Makefile"
