# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-devel
GH_TAGNAME=	072810c4aa7dbc30f01f9bf5ae3665e580c1d406
DISTINFO_FILE=	${.CURDIR}/distinfo
MASTERDIR=	${.CURDIR}/../forked-daapd

.include "${MASTERDIR}/Makefile"
