# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-devel
GH_TAGNAME=	0c3712629dad2fdeb5641815549f23774dbf34e9
DISTINFO_FILE=	${.CURDIR}/distinfo
MASTERDIR=	${.CURDIR}/../forked-daapd

.include "${MASTERDIR}/Makefile"
