# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	puppet_forge
PORTVERSION=	1.0.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Access and manipulate the Puppet Forge API from Ruby.

LICENSE=	APACHE20

RUN_DEPENDS=	${PKGNAMEPREFIX}her>=0.6:${PORTSDIR}/devel/rubygem-her

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
