# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	pthreads
PORTVERSION=	2.9.1
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEWARE}
MASTER_SITE_SUBDIR=	${PORTNAME}-win32
DISTNAME=	${PORTNAME}-w32-${PORTVERSION:S/./-/g}-release

MAINTAINER?=	takumiiinn@gmail.com
COMMENT?=	POSIX threads library for Windows compiled with MinGW-w64

USES=		gmake

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
