# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw-w64-i686-
PKGNAMESUFFIX=	-bootstrap
MAINTAINER=	takumiiinn@gmail.com
COMMENT=	GNU Compiler Collection 4.9 for MinGW-w64 i686

MASTERDIR=	${.CURDIR}/../mingw-gcc

.include "${MASTERDIR}/Makefile"
