# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PORTNAME=	xmd
PORTVERSION=	0.5
CATEGORIES=	sysutils
MASTER_SITES=	http://www.peach.ne.jp/archives/nas4free/xmd/
PKGNAMESUFFIX=	-kmod

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	Real-time Compression Memory Disk

LICENSE=	BSD2CLAUSE

USES=		kmod uidfix

WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}/${PORTNAME}

.include <bsd.port.mk>
