# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-x86_64-headers
COMMENT=	MinGW-w64 for x86_64 header files

MASTERDIR=	${.CURDIR}/../mingw-w64
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
