# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-x86_64-headers
MAINTAINER=	takumiiinn@gmail.com
COMMENT=	MinGW-w64 for x86_64 header files

MASTERDIR=	${.CURDIR}/../mingw-w64

.include "${MASTERDIR}/Makefile"
