# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-i686-pthreads
MAINTAINER=	takumiiinn@gmail.com
COMMENT?=	POSIX threads library for MinGW-w64 i686

MASTERDIR=	${.CURDIR}/../mingw-w64

.include "${MASTERDIR}/Makefile"
