# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

PKGNAMEPREFIX=	mingw-w64-i686-
MAINTAINER=	takumiiinn@gmail.com
COMMENT?=	POSIX threads library for Windows compiled with MinGW-w64 i686

MASTERDIR=	${.CURDIR}/../mingw-pthreads

.include "${MASTERDIR}/Makefile"
